name: CI Cypress UI Tests

on:
  push:
    branches-ignore:
      - staging*
      - feature/**
      - bug/**
      - chore/**
  pull_request:
    branches:
      - master
    types: [ opened, synchronize, ready_for_review ]

jobs:
  run_cypress:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false || github.ref == 'refs/heads/master' }}
    name: Run Cypress
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          npm install

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: npm run cypress-ci
          wait-on: "http://localhost:1234/nz/"
          config-file: cypress.json
          spec: "cypress/integration/**/*"
          wait-on-timeout: 300
          browser: chrome
          headless: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}